### ISSUE TITLE
Panel configutation

### ISSUE THREAD

**Issue by tomasb82** [algirdasc/hass-secolink#1]
Could you please indicate the configuration of the Secolink hardware?

**Comment by algirdasc** [comment]
You need to enable PSTN/GPRS reporting to your HASS IP address & port, don't forget to port forward in your router and add firewall rules. Let me know if you need more guidance.

**Comment by tomasb82** [comment]
Hi, 

I enabled LAN repoting to HA IP address on port 8125. Could you be more specific about port forward. Do I need make forward from Secolink IP to HA IP or samethng else?

**Comment by algirdasc** [comment]
You need to port forward 8125 port on your router to HA IP address.

**Comment by tomasb82** [comment]
sorry for mine obsession, but how to forward port on the same network. With my configutation HA and secolink is on the same network (192.168.1.160 for HA nd 192.168.1.110 for seco panel). Maybe I miss something on hardware configuration?

**Comment by tomasb82** [comment]
Hi in HA log I geting error. Maybe it will help

2021-03-17 18:25:04 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up secolink platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/secolink/alarm_control_panel.py", line 24, in setup_platform
    add_devices([SecolinkAlarm(
  File "/config/custom_components/secolink/alarm_control_panel.py", line 48, in __init__
    server = ThreadedTCPServer((self._listen_ip, self._listen_port), ThreadedTCPRequestHandler)
  File "/usr/local/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)

**Comment by algirdasc** [comment]
Is this full error? I cannot see exception message.

**Comment by tomasb82** [comment]
Hi, 

I have 4 isues with integration

1. 
Logger: homeassistant.loader
Source: loader.py:799
First occurred: 26 March 2021, 16:07:04 (2 occurrences)
Last logged: 26 March 2021, 16:07:05

You are using a custom integration secolink which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
You are using a custom integration platerecognizer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2.
Logger: homeassistant.components.alarm_control_panel
Source: custom_components/secolink/alarm_control_panel.py:48
Integration: Alarm Control Panel (documentation, issues)
First occurred: 26 March 2021, 16:07:05 (1 occurrences)
Last logged: 26 March 2021, 16:07:05

Error while setting up secolink platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/secolink/alarm_control_panel.py", line 24, in setup_platform
    add_devices([SecolinkAlarm(
  File "/config/custom_components/secolink/alarm_control_panel.py", line 48, in __init__
    server = ThreadedTCPServer((self._listen_ip, self._listen_port), ThreadedTCPRequestHandler)
  File "/usr/local/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Address not available

3.
Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:191
Integration: Alarm Control Panel (documentation, issues)
First occurred: 26 March 2021, 16:07:04 (1 occurrences)
Last logged: 26 March 2021, 16:07:04

AlarmControlPanel is deprecated, modify SecolinkAlarm to extend AlarmControlPanelEntity

4.
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 26 March 2021, 16:07:04 (1 occurrences)
Last logged: 26 March 2021, 16:07:04

No 'version' key in the manifest file for custom integration 'secolink'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'secolink'

**Comment by algirdasc** [comment]
You can safely ignore first one. Third and Fourth will be fixed in next commit.

Second one is the reason why you having problems. Could you also paste what configuration are you using for secolink panel?

**Comment by tomasb82** [comment]
![20210330_185014](https://user-images.githubusercontent.com/74060061/113106558-93638300-920b-11eb-902a-f26cb2160f54.jpg)
![20210330_184957](https://user-images.githubusercontent.com/74060061/113106577-98283700-920b-11eb-9c06-663ff70c13b7.jpg)

**Comment by algirdasc** [comment]
Hm, kodel mes lietuviškai nekalbam? Anyways, dar būtų gerai pamatyti kaip HA sukonfiguruotas secolink komponentas. Panašu, kad kažkas primaišyta ir pabandysim atsekti galus.

**Comment by tomasb82** [comment]
Galim ir lietuviškai :) 

alarm_control_panel:
  - platform: secolink
    name: Home
    listen_ip: 192.168.1.109
    listen_port: 8125
    clientid: 0000

**Comment by algirdasc** [comment]
O kodel tu `listen_ip` nurodai `192.168.1.109`, kai tavo HA IP'as yra `192.168.1.160`?

**Comment by tomasb82** [comment]
192.168.1.109  secolink panelės adresas.

**Comment by tomasb82** [comment]
pas mane raportavimas per LAN, gal čia kabliukas?

**Comment by algirdasc** [comment]
HA turi nurodyti IP, ant kurio bus "klausomasi" susijungimo. Paprastai, tai pačio HA IP adresas, tavo atveju `192.168.1.160`. Secolink panelėje turi nurodyti IP adresą, į kurį bus raportuojama, t.y. vel HA IP adresas - `192.168.8.1.160`.

**Comment by tomasb82** [comment]
Ok, pamėginsiu, duosiu žinoti.

**Comment by tomasb82** [comment]
panelę sukūrė :) Ačiū. Dar reikia vietoje ryšį pasitikrint vakar atjungiau kabelį ir matyti neįkišau :) duosiu žinoti

beje ar nebuvo bandymų zonas "išsitraukti"?

**Comment by algirdasc** [comment]
Nebandžiau, kadangi raportavimo protokolas šitos informacijos, kiek žinau, neraportuoja. Man užteko, kad tik signalizacijos statusą  raportuotų (pagal tai valdau šildymą / apšvietimą namuose).

**Comment by tomasb82** [comment]
Turiu dar klausymą. Man kažkodėl  ryšys su centrale dingsta po keleto minučių (routeris rodo kad offline) tačiau pingas į centralės IP eina.  Ištraukus fizikai laida ir vėl įkišus centralė prisijungia. iš/ į HA nenusiskaito. Gal teko susidurti? Gal reikia "versto" lan kabelio?

**Comment by algirdasc** [comment]
HA nuskaito tik ijungus / isjungus apsauga. Panasu, kad centrale "uzmiega". Pas mane raportuoja per GPRS, tai negaliu tiksliai pakomentuoti. Gal pamegink ijungti "heartbeat" ir centrale neuzmigs?

**Comment by tomasb82** [comment]
Dar keletas klaidų išmetė

1. 
Logger: custom_components.secolink.alarm_control_panel
Source: custom_components/secolink/alarm_control_panel.py:205
Integration: secolink (documentation, issues)
First occurred: 31 March 2021, 18:53:28 (190 occurrences)
Last logged: 18:06:36

Error parsing CSV IP message from 192.168.1.109

2.
Logger: custom_components.secolink.alarm_control_panel
Source: custom_components/secolink/alarm_control_panel.py:206
Integration: secolink (documentation, issues)
First occurred: 31 March 2021, 18:53:28 (190 occurrences)
Last logged: 18:06:36

Error: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

3.
Logger: custom_components.secolink.alarm_control_panel
Source: custom_components/secolink/alarm_control_panel.py:206
Integration: secolink (documentation, issues)
First occurred: 31 March 2021, 18:53:28 (190 occurrences)
Last logged: 18:06:36

Error: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

4.
Logger: custom_components.secolink.alarm_control_panel
Source: custom_components/secolink/alarm_control_panel.py:207
Integration: secolink (documentation, issues)
First occurred: 31 March 2021, 18:53:28 (190 occurrences)
Last logged: 18:06:36

Line: 130

**Comment by paulius2k** [comment]
Sveiki,
@algirdasc - ar visa ši aprašyta integracija veikia per Secolink modulį GSV6U?

**Comment by algirdasc** [comment]
> Sveiki,
> @algirdasc - ar visa ši aprašyta integracija veikia per Secolink modulį GSV6U?

Taip. Aš asmeniškai į HA per GPRS raportavimą gaunu signalizacijos būseną.

**Comment by tomasb82** [comment]
labas. Gal išėjo pasidomėti dėl klaidų per LAN modulį?

**Comment by algirdasc** [comment]
Labas, ne, nepasidomejau. Siek tiek uzleidau sita moduli. Bet jei aktualu, galima bandyti paziureti kokius raw duomenis gauni, ir bandyti kazka pritaikyti. Jei https://github.com/algirdasc/hass-secolink/blob/master/custom_components/secolink/alarm_control_panel.py faile, 129 eiluteje pridetum:
`_LOGGER.debug("data: {0}".format(data))`
ir ijungtum hass-secolink modulio debug'a, galima paziureti ka ten siuncia/gauna tavo LAN modulis.

**Comment by tomasb82** [comment]
Sveikas, 

eilute pridėjau  
![image](https://user-images.githubusercontent.com/74060061/148089797-d45062c9-3e11-469b-8524-7bda813c4834.png)

Kaip įjungti debug'ą?

**Comment by algirdasc** [comment]
Home Assistant config'e, prie log'o turi nurodyti:

```
logger:
  default: warn
  logs:
    custom_components.secolink.alarm_control_panel: debug
```

Svarbiausia yra:

```
  logs:
    custom_components.secolink.alarm_control_panel: debug
```

Visa kita, jei nusistates kazkaip custom - gali palikti.

**Comment by tomasb82** [comment]
![image](https://user-images.githubusercontent.com/74060061/148115669-192eb6dc-1cfc-4978-954e-9f28ab174277.png)

data: b'\xc4\xd71\x001234181628A1AA17C05E6F0019C0'

**Comment by tomasb82** [comment]
gal pagelbės

**Comment by algirdasc** [comment]
O daugiau jokios info neprasiuncia? Atrodo, kad visai kitas protokolas naudojamas.

**Comment by tomasb82** [comment]
Ne, tik viena šita eilute

**Comment by algirdasc** [comment]
Ir jis ta pati siuncia pastoviai? Ar kazkas keiciasi? Kokie dar galimi pasirinkti protokolai centraleje? Dabar matau pasirinktas E2 is auksciau pateiktu foto.

**Comment by tomasb82** [comment]
Taip, visa laika ta pati. Protokolas pagal tavo integracija. Rytojbpaziuresiu kas dar yra

**Comment by algirdasc** [comment]
Na as dabar tiksliau nepamenu, koks pas mane protokolas nustatytas, bet nepamenu, kad butu E2.

**Comment by tomasb82** [comment]
Yra tokie protokolai E2, CSV IP, Fibro, SIA

**Comment by algirdasc** [comment]
Pasirink CSV IP ir turetu vaziuoti.

**Comment by algirdasc** [comment]
Ar suveike?

**Comment by tomasb82** [comment]
Labas, dabar kitoks eroras


2022-01-13 10:54:03 DEBUG (Thread-579) [custom_components.secolink.alarm_control_panel] data: b',,1234,18340101001\x00'
2022-01-13 10:54:03 WARNING (Thread-579) [custom_components.secolink.alarm_control_panel] Received unknown message from 192.168.1.109: ,,1234,18340101001

**Comment by tomasb82** [comment]
gal pavyko pažiūrėti dėl klaidos?
